define object_dialogue = {
    # ITEM          DIALOGUE
    #       Living Room
    "apple":        "I don't have the appetite for that.",
    "bulb":         "Why is this thing lying around here?.",
    "chime":        "Ah, that annoying thing. Better leave it up there.",
    "correctPlant": "There’s a piece of paper. It says{b} _ _ _ 1{/b}",
    "drawerLvrm":   "There’s a key!",
    "faceshield":   "Got it.",
    "headphone":    "Pretty cool, but I'll leave it here.",
    "keyboard":     "Neat-looking keyboard and mouse.",
    "lamp":         "Not really needed to open right now.",
    "monitor":      "This monitor is handsome.",
    "mugs":         "Empty.",
    "pencil":       "A thick looking pencil.",
    "pictureLvrm":  "There’s something written at the corner of the frame. \n{b}7 _ _ _{/b}",
    "screws":       "Really? First a bulb, and now screws?!",
    "shoes":        "Mom's fancy sandals.",
    "tablet":       "Mehhh, maybe later.",
    "trumpet":      "I do not feel playing it.",
    "tv":           "Not in the mood to watch TV.",
    "unit":         "Might need to dust it off later.",
    "wrongPlant":   "A healthy looking plant.",
    #        Bed room
    "bed":          "I can sleep later",
    "books":        "No time to read",
    "drawerBdrm":   "It’s locked.",
    "drawerhaskey": "I opened the drawer with the key from the living room.",
    "dumbell":      "Just some dumbells.",
    "facemask":     "Here's my {b}facemask{/b}.",
    "facemask2":    "I already got my {b}facemask{/b} here.",
    "gameboy":      "I can't right now.",
    "lampB":         "A desk lamp.",
    "laptop":       "Haven't finished my work yet.",
    "phone":        "I have {b}0{/b} new messages.",
    "pencilCan":    "Here are the pencils, why is the thick one in the living room?.",
    "pictureBdrm":  "There’s something written at the corner of the frame. \n{b}_ _ 2 _{/b}",
    "pillow":       "Comfies, I'll cuddle with you later.",
    "plant":        "The house plants are growing quite nicely",
    "poster":       "Oh hey, a poster!.",
    "sofa":         "Maybe later.",
    "studyTable":   "Pens, papers and box that looks like it needs a 4-digit code to unlock.",
    "studyTable2":  "I got my {b}wallet{/b}.",
    "studyTable3":  "I already got my {b}wallet{/b} here.",
    "window":       "Nothing to see here.",
    #        Kitchen
    "bread":        "Good-tasting bread even without stuffing.",
    "broom":         "Hello, my friend.",
    "cans":         "Nope",
    "faucet":       "Not a time to wash my hands.",
    "greenApple":   "Tasty, just not in a mood to eat.",
    "milk":         "Tasty, but maybe later.",
    "mugs":         "Oopsie, fragiles.",
    "painting":     "What is the masterpiece doing in here?.",
    "plant":        "What a decoration, even in the kitchen.",
    "sanitizer":    "Here’s my hand sanitizer.",
    "saucepan":     "Shiny!.",
    "tissue":       "Oh, might come in handy.",
    "tray":         "A tray lying on the floor.",
}
